// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEPuH9aMLXfo7mRhCFb-ztkR-TyYkAklc',
    appId: '1:1025550643354:web:ab62364c225095fd252f23',
    messagingSenderId: '1025550643354',
    projectId: 'scrapuncle-b4b06',
    authDomain: 'scrapuncle-b4b06.firebaseapp.com',
    storageBucket: 'scrapuncle-b4b06.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvgenj1eQ8UJgzpyAbrbJSieyMgKYAZPE',
    appId: '1:1025550643354:android:ffbff5c9e5c29ff7252f23',
    messagingSenderId: '1025550643354',
    projectId: 'scrapuncle-b4b06',
    storageBucket: 'scrapuncle-b4b06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1IfNvvX401Fctr5udRDtamw-cDerwEr0',
    appId: '1:1025550643354:ios:a92a6bf166155b1c252f23',
    messagingSenderId: '1025550643354',
    projectId: 'scrapuncle-b4b06',
    storageBucket: 'scrapuncle-b4b06.firebasestorage.app',
    iosBundleId: 'com.example.scrapuncleFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1IfNvvX401Fctr5udRDtamw-cDerwEr0',
    appId: '1:1025550643354:ios:a92a6bf166155b1c252f23',
    messagingSenderId: '1025550643354',
    projectId: 'scrapuncle-b4b06',
    storageBucket: 'scrapuncle-b4b06.firebasestorage.app',
    iosBundleId: 'com.example.scrapuncleFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEPuH9aMLXfo7mRhCFb-ztkR-TyYkAklc',
    appId: '1:1025550643354:web:33089932207a3e9e252f23',
    messagingSenderId: '1025550643354',
    projectId: 'scrapuncle-b4b06',
    authDomain: 'scrapuncle-b4b06.firebaseapp.com',
    storageBucket: 'scrapuncle-b4b06.firebasestorage.app',
  );
}
